---
platform: linux

image: docker:///cloudfoundry/inigo-ci

params:
  RECEPTOR_ADDRESS: http://10.244.17.6:8888
  ROUTABLE_DOMAIN_SUFFIX: 10.244.0.34.xip.io

inputs:
  - name: vizzini
    path: gopath/src/github.com/cloudfoundry-incubator/vizzini

run:
  path: gopath/src/github.com/cloudfoundry-incubator/vizzini/scripts/ci/run-vizzini
